/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v14.0
processor: MIMXRT1062xxxxB
package_id: MIMXRT1062DVL6B
mcu_data: ksdk2_0
processor_version: 15.0.1
board: MIMXRT1060-EVKC
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 96c1cec6-3bd3-47a2-8301-f38e4b0dd25f
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - commonSetting:
    - HAL_GPIO_ISR_PRIORITY: '3'
    - HAL_GpioPreInit: 'true'
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic_57b5eef3774cc60acaede6f5b8bddc67'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * GPIO1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO1'
- type: 'igpio_adapter'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'igpio_adapter_5c0a3d4fd4d107e507335b7419af3b4f'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO1'
- config_sets:
  - fsl_adapter_gpio:
    - signalsFilter: 'default boot'
    - gpioSignalsParameters:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
      - 9: []
      - 10: []
      - 11: []
      - 12: []
      - 13: []
    - gpioPinsOverView:
      - 0: []
      - 1: []
      - 2: []
      - 3: []
      - 4: []
      - 5: []
      - 6: []
      - 7: []
      - 8: []
    - gpioPinsConfig:
      - 0:
        - pin_selection: 'gpio_io.02'
        - userPinId: 'PPS'
        - funtionalGroupEnum: 'BOARD_InitPins'
        - setCallbackFnc: 'true'
        - callbackFncCfg:
          - functionName: 'custom:PPS_Handler'
          - userData: ''
      - 1:
        - pin_selection: 'gpio_io.03'
        - userPinId: 'TIMEPULSE'
        - funtionalGroupEnum: 'BOARD_InitPins'
        - setCallbackFnc: 'true'
        - callbackFncCfg:
          - functionName: 'custom:TIMEPULSE_Handler'
          - userData: ''
      - 2:
        - pin_selection: 'gpio_io.24'
        - userPinId: 'MODEM_DTR'
        - funtionalGroupEnum: 'BOARD_InitPins'
        - setCallbackFnc: 'false'
        - callbackFncCfg:
          - functionName: 'defaultFunctionName'
          - userData: ''
    - globalCfg: []
    - differentPeripheralsAdd: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
/* Get GPIO pin configuration */
hal_gpio_pin_config_t createAdapterGpioPinConfig(GPIO_Type *port, uint8_t pin, hal_gpio_direction_t direction, uint8_t level){
  hal_gpio_pin_config_t temp;
  /* Array of GPIO peripheral base address. */
  static GPIO_Type *const s_gpioBases[] = GPIO_BASE_PTRS;
  uint8_t portInd;
  /* Find the port index from base address mappings. */
  for (portInd = 0U; portInd < ARRAY_SIZE(s_gpioBases); portInd++)
  {    if (s_gpioBases[portInd] == port)
    {
      break;
    }
  }
  
  assert(portInd < ARRAY_SIZE(s_gpioBases));
  
  temp.direction = direction;
  temp.level = level;
  temp.port = portInd;
  temp.pin = pin;
  
  return temp;
};
GPIO_HANDLE_DEFINE(GPIO1_PPS_handle);
GPIO_HANDLE_DEFINE(GPIO1_TIMEPULSE_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_SPI_CS2_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_FAN_CONTROL_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_BUZZER_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_MODEM_PWR_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_TRIGGER_handle);
GPIO_HANDLE_DEFINE(GPIO1_MODEM_DTR_handle);
GPIO_HANDLE_DEFINE(BOARD_INITPINS_SPI_CS_handle);

static void GPIO1_init(void) {
  /* GPIO adapter initialization */
  static hal_gpio_pin_config_t gpioPinConfig;
  hal_gpio_status_t status;
  (void)status; // suppress warning in the run configuration
  /* gpio_io, 02 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(GPIO1_PPS_PORT, GPIO1_PPS_PIN, GPIO1_PPS_PIN_DIRECTION, GPIO1_PPS_PIN_LEVEL);
  status = HAL_GpioInit(GPIO1_PPS_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  status = HAL_GpioInstallCallback(GPIO1_PPS_handle, PPS_Handler, NULL);
  assert(status == kStatus_HAL_GpioSuccess);
  status = HAL_GpioSetTriggerMode(GPIO1_PPS_handle, GPIO1_PPS_TRIGGER_MODE);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 03 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(GPIO1_TIMEPULSE_PORT, GPIO1_TIMEPULSE_PIN, GPIO1_TIMEPULSE_PIN_DIRECTION, GPIO1_TIMEPULSE_PIN_LEVEL);
  status = HAL_GpioInit(GPIO1_TIMEPULSE_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  status = HAL_GpioInstallCallback(GPIO1_TIMEPULSE_handle, TIMEPULSE_Handler, NULL);
  assert(status == kStatus_HAL_GpioSuccess);
  status = HAL_GpioSetTriggerMode(GPIO1_TIMEPULSE_handle, GPIO1_TIMEPULSE_TRIGGER_MODE);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 04 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_SPI_CS2_PORT, BOARD_INITPINS_SPI_CS2_PIN, BOARD_INITPINS_SPI_CS2_PIN_DIRECTION, BOARD_INITPINS_SPI_CS2_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_SPI_CS2_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 20 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_FAN_CONTROL_PORT, BOARD_INITPINS_FAN_CONTROL_PIN, BOARD_INITPINS_FAN_CONTROL_PIN_DIRECTION, BOARD_INITPINS_FAN_CONTROL_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_FAN_CONTROL_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 21 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_BUZZER_PORT, BOARD_INITPINS_BUZZER_PIN, BOARD_INITPINS_BUZZER_PIN_DIRECTION, BOARD_INITPINS_BUZZER_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_BUZZER_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 22 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_MODEM_PWR_PORT, BOARD_INITPINS_MODEM_PWR_PIN, BOARD_INITPINS_MODEM_PWR_PIN_DIRECTION, BOARD_INITPINS_MODEM_PWR_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_MODEM_PWR_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 23 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_TRIGGER_PORT, BOARD_INITPINS_TRIGGER_PIN, BOARD_INITPINS_TRIGGER_PIN_DIRECTION, BOARD_INITPINS_TRIGGER_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_TRIGGER_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  status = HAL_GpioSetTriggerMode(BOARD_INITPINS_TRIGGER_handle, BOARD_INITPINS_TRIGGER_TRIGGER_MODE);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 24 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(GPIO1_MODEM_DTR_PORT, GPIO1_MODEM_DTR_PIN, GPIO1_MODEM_DTR_PIN_DIRECTION, GPIO1_MODEM_DTR_PIN_LEVEL);
  status = HAL_GpioInit(GPIO1_MODEM_DTR_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
  /* gpio_io, 28 signal initialization */
  gpioPinConfig = createAdapterGpioPinConfig(BOARD_INITPINS_SPI_CS_PORT, BOARD_INITPINS_SPI_CS_PIN, BOARD_INITPINS_SPI_CS_PIN_DIRECTION, BOARD_INITPINS_SPI_CS_PIN_LEVEL);
  status = HAL_GpioInit(BOARD_INITPINS_SPI_CS_handle, &gpioPinConfig);
  assert(status == kStatus_HAL_GpioSuccess);
}

/***********************************************************************************************************************
 * LPI2C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPI2C1'
- type: 'lpi2c'
- mode: 'master'
- custom_name_enabled: 'false'
- type_id: 'lpi2c_6b71962515c3208facfccd030afebc98'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPI2C1'
- config_sets:
  - main:
    - clockSource: 'Lpi2cClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
  - interrupt_vector: []
  - master:
    - mode: 'transfer'
    - config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - edmaRequestSources: ''
    - transfer:
      - blocking: 'false'
      - enable_custom_handle: 'false'
      - callback:
        - name: ''
        - userData: ''
      - flags: ''
      - slaveAddress: '0'
      - direction: 'kLPI2C_Write'
      - subaddress: '0'
      - subaddressSize: '1'
      - blocking_buffer: 'false'
      - enable_custom_buffer: 'false'
      - dataSize: '1'
    - quick_selection: 'qs_master_transfer'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LPI2C1_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
lpi2c_master_transfer_t LPI2C1_masterTransfer = {
  .flags = kLPI2C_TransferDefaultFlag,
  .slaveAddress = 0,
  .direction = kLPI2C_Write,
  .subaddress = 0,
  .subaddressSize = 1,
  .data = LPI2C1_masterBuffer,
  .dataSize = 1
};
lpi2c_master_handle_t LPI2C1_masterHandle;
uint8_t LPI2C1_masterBuffer[LPI2C1_MASTER_BUFFER_SIZE];

static void LPI2C1_init(void) {
  LPI2C_MasterInit(LPI2C1_PERIPHERAL, &LPI2C1_masterConfig, LPI2C1_CLOCK_FREQ);
  LPI2C_MasterTransferCreateHandle(LPI2C1_PERIPHERAL, &LPI2C1_masterHandle, NULL, NULL);
}

/***********************************************************************************************************************
 * LPUART1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPUART1'
- type: 'lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpuart_65a7af1f2e04f737cb1c75e9f68585ac'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPUART1'
- config_sets:
  - lpuartConfig_t:
    - lpuartConfig:
      - clockSource: 'LpuartClock'
      - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStopBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableTx: 'true'
      - enableRx: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LPUART1_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStopBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableTx = true,
  .enableRx = true
};

static void LPUART1_init(void) {
  LPUART_Init(LPUART1_PERIPHERAL, &LPUART1_config, LPUART1_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * LPSPI3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LPSPI3'
- type: 'lpspi'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpspi_3b8318dca8e0034b76e041f04d445c24'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LPSPI3'
- config_sets:
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'LpspiClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master:
      - baudRate: '1000000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseSecondEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '1000'
      - lastSckToPcsDelayInNanoSec: '1000'
      - betweenTransferDelayInNanoSec: '1000'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - pcsFunc: 'kLPSPI_PcsAsData'
      - dataOutConfig: 'kLpspiDataOutRetained'
      - enableInputDelay: 'false'
    - set_FifoWaterMarks: 'false'
    - fifoWaterMarks:
      - txWatermark: '0'
      - rxWatermark: '0'
    - allPcsPolarityEnable: 'false'
    - allPcsPolarity:
      - kLPSPI_Pcs1Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs2Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs3Active: 'kLPSPI_PcsActiveLow'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LPSPI3_config = {
  .baudRate = 1000000UL,
  .bitsPerFrame = 8UL,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseSecondEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 1000UL,
  .lastSckToPcsDelayInNanoSec = 1000UL,
  .betweenTransferDelayInNanoSec = 1000UL,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .pcsFunc = kLPSPI_PcsAsData,
  .dataOutConfig = kLpspiDataOutRetained,
  .enableInputDelay = false
};

static void LPSPI3_init(void) {
  LPSPI_MasterInit(LPSPI3_PERIPHERAL, &LPSPI3_config, LPSPI3_CLOCK_FREQ);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  /* GPIO adapter pre-initialization */
  HAL_GpioPreInit();

  /* Initialize components */
  GPIO1_init();
  LPI2C1_init();
  LPUART1_init();
  LPSPI3_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
