/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: MIMXRT1062xxxxB
package_id: MIMXRT1062DVL6B
mcu_data: ksdk2_0
processor_version: 15.0.1
board: MIMXRT1060-EVKC
external_user_signals: {}
pin_labels:
- {pin_num: E3, pin_signal: GPIO_EMC_00, label: 'SEMC_D0/U16[A8]', identifier: SEMC_D0;USB_STATUS}
- {pin_num: A11, pin_signal: GPIO_B1_00, label: 'LCDIF_D12/J49[A9]', identifier: LCDIF_D12;USB_DTR}
- {pin_num: D13, pin_signal: GPIO_B1_12, label: 'SD_CD_SW/J22[9]', identifier: SD_CD_SW;LPUART5;UART5_TXD}
- {pin_num: D14, pin_signal: GPIO_B1_13, label: 'WDOG_B/U27[3]', identifier: WDOG_B;UART5_RXD}
- {pin_num: H10, pin_signal: GPIO_AD_B0_01, label: 'USB_OTG1_ID/J48[4]/BT_WAKE_B_3V3/J8[20]/DC_INT/J23[3]', identifier: NRF_READY}
- {pin_num: M11, pin_signal: GPIO_AD_B0_02, label: 'USB_OTG1_PWR/J17[2]/U30[A1]/LCD_RST/J49[B2]/DC_RESET/J23[7]/U9[5]', identifier: PPS}
- {pin_num: G11, pin_signal: GPIO_AD_B0_03, label: 'USB_OTG1_OC/J17[1]/U30[A2]/DC_GPIO2/J23[22]/U10[19]', identifier: Timepulse;TIMEPULSE}
- {pin_num: F11, pin_signal: GPIO_AD_B0_04, label: 'DC_I2S2_TX_SYNC/J19[9]/BOOT_MODE[0]', identifier: DC_I2S2_TX_SYNC;SPI_CS2}
- {pin_num: J11, pin_signal: GPIO_AD_B1_00, label: 'I2C1_SCL/J49[B4]/U369[F1]/U115[4]/J33[6]/J17[10]/CSI_I2C_SCL/J46[20]', identifier: I2C_SCL_FXOS8700CQ;CSI_I2C_SCL;I2C_SCL}
- {pin_num: K11, pin_signal: GPIO_AD_B1_01, label: 'I2C1_SDA/J49[B5]/U369[E2]/U115[6]/J33[5]/J17[9]/CSI_I2C_SDA/J46[22]', identifier: I2C_SDA_FXOS8700CQ;CSI_I2C_SDA;I2C_SDA}
- {pin_num: L11, pin_signal: GPIO_AD_B1_02, label: 'SPDIF_OUT/J18[2]/BT_RST#/J8[54]/CSI_PWDN/PWDN/J46[17]/J16[7]', identifier: SPDIF_OUT;UART2_TXD}
- {pin_num: M12, pin_signal: GPIO_AD_B1_03, label: 'SPDIF_IN/U15[4]/WL_RST#/J8[56]/SD_PWREN/Q5[1]/J16[8]', identifier: SPDIF_IN;UART2_TXD;UART2_RXD}
- {pin_num: H13, pin_signal: GPIO_AD_B1_08, label: 'AUD_INT/J34[5]/U369[E3]/WIFI_RST_B/U9[3]/CSI_D9/J46[13]/J16[4]', identifier: CSI_D9;MODEM_DTR}
- {pin_num: L13, pin_signal: GPIO_AD_B1_10, label: 'SAI1_RX_SYNC/J23[9]/CSI_D7/J46[9]/J33[1]', identifier: CSI_D7;UART8_TXD}
- {pin_num: J13, pin_signal: GPIO_AD_B1_11, label: 'DC_I2S1_RX_BCLK/J23[5]/CSI_D6/J46[7]/J33[2]', identifier: CSI_D6;UART8_RXD}
- {pin_num: H12, pin_signal: GPIO_AD_B1_12, label: 'SAI1_RXD/J41[1]/DC_I2S1_RX_D0/J23[11]/BT_PCM_RXD/U10[18]/CSI_D5/J46[5]', identifier: CSI_D5;SPI_CS}
- {pin_num: H11, pin_signal: GPIO_AD_B1_13, label: 'SAI1_TXD/J37[1]/DC_I2S1_TX_D0/J23[17]/BT_PCM_TXD/U9[6]/CSI_D4/J46[3]', identifier: CSI_D4;SPI_SDI}
- {pin_num: G12, pin_signal: GPIO_AD_B1_14, label: 'SAI1_TX_BCLK/J35[1]/DC_I2S1_TX_BCLK/U23[23]/BT_PCM_BCLK/U9[7]/U10[17]/CSI_D3/J46[4]', identifier: CSI_D3;SPI_SDO}
- {pin_num: J14, pin_signal: GPIO_AD_B1_15, label: 'SAI1_TX_SYNC/J36[1]/DC_I2S1_TX_SYNC/U23[16]/BT_PCM_SYNC/U9[8]/U10[16]/CSI_D2/J46[6]', identifier: CSI_D2;SPI_CLK}
- {pin_num: J1, pin_signal: GPIO_SD_B0_02, label: 'SD1_D0/J22[7]/J17[4]', identifier: SD1_D0;NRF_READY}
- {pin_num: K1, pin_signal: GPIO_SD_B0_03, label: 'SD1_D1/J22[8]/J17[5]', identifier: SD1_D1;READER_SHUTDOWN}
- {pin_num: J2, pin_signal: GPIO_SD_B0_05, label: 'SD1_D3/J22[2]', identifier: SD1_D3;READER_PWR}
- {pin_num: M3, pin_signal: GPIO_SD_B1_02, label: 'FlexSPI_D1_B/U20[E3]', identifier: FlexSPI_D1_B;NRF_READY}
- {pin_num: P2, pin_signal: GPIO_SD_B1_04, label: 'FlexSPI_CLK_B/U20[B1]', identifier: FlexSPI_CLK_B;BUTTON_LED}
- {pin_num: L12, pin_signal: GPIO_AD_B1_04, label: 'CSI_PIXCLK/J46[8]/BT_DEV_WAKE/BT_UART_CTS/U9[9]/J33[3]', identifier: CSI_PIXCLK;FAN_CONTROL}
- {pin_num: K12, pin_signal: GPIO_AD_B1_05, label: 'CSI_MCLK/J46[12]/WL_DEV_WAKE/BT_UART_RTS/U9[10]/J33[4]', identifier: CSI_MCLK;BUZZER}
- {pin_num: J12, pin_signal: GPIO_AD_B1_06, label: 'CSI_VSYNC/J46[18]/BT_UART_TXD/U9[4]/I2C3_SCL/J24[3]/J23[13]/J16[2]', identifier: CSI_VSYNC;MODEM_PWR}
- {pin_num: K10, pin_signal: GPIO_AD_B1_07, label: 'CSI_HSYNC/J46[16]/BT_UART_RXD/U10[20]/I2C3_SDA/J24[5]/J23[15]/J16[1]', identifier: CSI_HSYNC;TRIGGER}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: K11, peripheral: LPI2C1, signal: SDA, pin_signal: GPIO_AD_B1_01, identifier: I2C_SDA, software_input_on: Enable, hysteresis_enable: Disable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Disable, open_drain: Enable, speed: MHZ_100_01, drive_strength: R0_6, slew_rate: Fast}
  - {pin_num: J11, peripheral: LPI2C1, signal: SCL, pin_signal: GPIO_AD_B1_00, identifier: I2C_SCL, software_input_on: Enable, pull_up_down_config: Pull_Up_22K_Ohm,
    pull_keeper_select: Pull, pull_keeper_enable: Disable, open_drain: Enable, speed: MHZ_100_01, drive_strength: R0_6, slew_rate: Fast}
  - {pin_num: M11, peripheral: GPIO1, signal: 'gpio_io, 02', pin_signal: GPIO_AD_B0_02, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge, software_input_on: Enable,
    pull_up_down_config: Pull_Down_100K_Ohm, pull_keeper_select: Pull, pull_keeper_enable: Disable, open_drain: Disable, speed: MHZ_100, slew_rate: Fast}
  - {pin_num: G11, peripheral: GPIO1, signal: 'gpio_io, 03', pin_signal: GPIO_AD_B0_03, identifier: TIMEPULSE, direction: INPUT, gpio_interrupt: kGPIO_IntFallingEdge,
    software_input_on: Enable, pull_up_down_config: Pull_Down_100K_Ohm, pull_keeper_select: Pull, pull_keeper_enable: Disable, open_drain: Disable}
  - {pin_num: L14, peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_13, software_input_on: Enable, pull_keeper_enable: Enable}
  - {pin_num: K14, peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_12, software_input_on: Enable}
  - {pin_num: H13, peripheral: GPIO1, signal: 'gpio_io, 24', pin_signal: GPIO_AD_B1_08, identifier: MODEM_DTR, direction: OUTPUT, gpio_init_state: 'true', software_input_on: Enable,
    pull_up_down_config: Pull_Up_100K_Ohm, pull_keeper_select: Pull, pull_keeper_enable: Disable}
  - {pin_num: J14, peripheral: LPSPI3, signal: SCK, pin_signal: GPIO_AD_B1_15, identifier: SPI_CLK, direction: OUTPUT, speed: MHZ_100_01, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: H12, peripheral: GPIO1, signal: 'gpio_io, 28', pin_signal: GPIO_AD_B1_12, identifier: SPI_CS, direction: OUTPUT, speed: MHZ_100_01, drive_strength: R0_7,
    slew_rate: Fast}
  - {pin_num: F11, peripheral: GPIO1, signal: 'gpio_io, 04', pin_signal: GPIO_AD_B0_04, identifier: SPI_CS2, direction: OUTPUT, pull_keeper_select: Keeper, speed: MHZ_100_01,
    drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: G12, peripheral: LPSPI3, signal: SDO, pin_signal: GPIO_AD_B1_14, identifier: SPI_SDO, speed: MHZ_100_01, drive_strength: R0_7, slew_rate: Fast}
  - {pin_num: H11, peripheral: LPSPI3, signal: SDI, pin_signal: GPIO_AD_B1_13, identifier: SPI_SDI, hysteresis_enable: Enable, pull_keeper_enable: Enable}
  - {pin_num: D14, peripheral: LPUART5, signal: RX, pin_signal: GPIO_B1_13, identifier: UART5_RXD}
  - {pin_num: D13, peripheral: LPUART5, signal: TX, pin_signal: GPIO_B1_12, identifier: UART5_TXD}
  - {pin_num: L13, peripheral: LPUART8, signal: TX, pin_signal: GPIO_AD_B1_10, identifier: UART8_TXD}
  - {pin_num: J13, peripheral: LPUART8, signal: RX, pin_signal: GPIO_AD_B1_11, identifier: UART8_RXD}
  - {pin_num: L11, peripheral: LPUART2, signal: TX, pin_signal: GPIO_AD_B1_02, identifier: UART2_TXD}
  - {pin_num: M12, peripheral: LPUART2, signal: RX, pin_signal: GPIO_AD_B1_03, identifier: UART2_RXD}
  - {pin_num: K12, peripheral: GPIO1, signal: 'gpio_io, 21', pin_signal: GPIO_AD_B1_05, identifier: BUZZER, direction: OUTPUT}
  - {pin_num: K1, peripheral: GPIO3, signal: 'gpio_io, 15', pin_signal: GPIO_SD_B0_03, identifier: READER_SHUTDOWN, direction: OUTPUT}
  - {pin_num: L12, peripheral: GPIO1, signal: 'gpio_io, 20', pin_signal: GPIO_AD_B1_04, identifier: FAN_CONTROL, direction: OUTPUT}
  - {pin_num: J2, peripheral: GPIO3, signal: 'gpio_io, 17', pin_signal: GPIO_SD_B0_05, identifier: READER_PWR, direction: OUTPUT, pull_up_down_config: no_init}
  - {pin_num: J12, peripheral: GPIO1, signal: 'gpio_io, 22', pin_signal: GPIO_AD_B1_06, identifier: MODEM_PWR, direction: OUTPUT, pull_keeper_enable: Disable}
  - {pin_num: P2, peripheral: GPIO3, signal: 'gpio_io, 04', pin_signal: GPIO_SD_B1_04, identifier: BUTTON_LED, direction: OUTPUT, gpio_init_state: 'true', pull_up_down_config: no_init,
    pull_keeper_enable: Disable}
  - {pin_num: K10, peripheral: GPIO1, signal: 'gpio_io, 23', pin_signal: GPIO_AD_B1_07, identifier: TRIGGER, direction: INPUT, gpio_interrupt: kGPIO_IntRisingEdge,
    pull_keeper_select: Keeper, speed: MHZ_200}
  - {pin_num: E3, peripheral: GPIO4, signal: 'gpio_io, 00', pin_signal: GPIO_EMC_00, identifier: USB_STATUS, direction: INPUT}
  - {pin_num: A11, peripheral: GPIO2, signal: 'gpio_io, 16', pin_signal: GPIO_B1_00, identifier: USB_DTR, direction: OUTPUT}
  - {pin_num: H10, peripheral: GPIO1, signal: 'gpio_io, 01', pin_signal: GPIO_AD_B0_01, direction: INPUT, software_input_on: Enable, pull_keeper_select: Pull}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : 
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           

  /* GPIO configuration of NRF_READY on GPIO_AD_B0_01 (pin H10) */
  gpio_pin_config_t NRF_READY_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_01 (pin H10) */
  GPIO_PinInit(GPIO1, 1U, &NRF_READY_config);

  /* GPIO configuration of PPS on GPIO_AD_B0_02 (pin M11) */
  gpio_pin_config_t PPS_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_02 (pin M11) */
  GPIO_PinInit(GPIO1, 2U, &PPS_config);
  /* Enable GPIO pin interrupt on GPIO_AD_B0_02 (pin M11) */
  GPIO_PortEnableInterrupts(GPIO1, 1U << 2U);

  /* GPIO configuration of TIMEPULSE on GPIO_AD_B0_03 (pin G11) */
  gpio_pin_config_t TIMEPULSE_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntFallingEdge
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_03 (pin G11) */
  GPIO_PinInit(GPIO1, 3U, &TIMEPULSE_config);
  /* Enable GPIO pin interrupt on GPIO_AD_B0_03 (pin G11) */
  GPIO_PortEnableInterrupts(GPIO1, 1U << 3U);

  /* GPIO configuration of SPI_CS2 on GPIO_AD_B0_04 (pin F11) */
  gpio_pin_config_t SPI_CS2_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B0_04 (pin F11) */
  GPIO_PinInit(GPIO1, 4U, &SPI_CS2_config);

  /* GPIO configuration of FAN_CONTROL on GPIO_AD_B1_04 (pin L12) */
  gpio_pin_config_t FAN_CONTROL_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_04 (pin L12) */
  GPIO_PinInit(GPIO1, 20U, &FAN_CONTROL_config);

  /* GPIO configuration of BUZZER on GPIO_AD_B1_05 (pin K12) */
  gpio_pin_config_t BUZZER_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_05 (pin K12) */
  GPIO_PinInit(GPIO1, 21U, &BUZZER_config);

  /* GPIO configuration of MODEM_PWR on GPIO_AD_B1_06 (pin J12) */
  gpio_pin_config_t MODEM_PWR_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_06 (pin J12) */
  GPIO_PinInit(GPIO1, 22U, &MODEM_PWR_config);

  /* GPIO configuration of TRIGGER on GPIO_AD_B1_07 (pin K10) */
  gpio_pin_config_t TRIGGER_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_IntRisingEdge
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_07 (pin K10) */
  GPIO_PinInit(GPIO1, 23U, &TRIGGER_config);
  /* Enable GPIO pin interrupt on GPIO_AD_B1_07 (pin K10) */
  GPIO_PortEnableInterrupts(GPIO1, 1U << 23U);

  /* GPIO configuration of MODEM_DTR on GPIO_AD_B1_08 (pin H13) */
  gpio_pin_config_t MODEM_DTR_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_08 (pin H13) */
  GPIO_PinInit(GPIO1, 24U, &MODEM_DTR_config);

  /* GPIO configuration of SPI_CS on GPIO_AD_B1_12 (pin H12) */
  gpio_pin_config_t SPI_CS_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_AD_B1_12 (pin H12) */
  GPIO_PinInit(GPIO1, 28U, &SPI_CS_config);

  /* GPIO configuration of USB_DTR on GPIO_B1_00 (pin A11) */
  gpio_pin_config_t USB_DTR_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_B1_00 (pin A11) */
  GPIO_PinInit(GPIO2, 16U, &USB_DTR_config);

  /* GPIO configuration of BUTTON_LED on GPIO_SD_B1_04 (pin P2) */
  gpio_pin_config_t BUTTON_LED_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 1U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B1_04 (pin P2) */
  GPIO_PinInit(GPIO3, 4U, &BUTTON_LED_config);

  /* GPIO configuration of READER_SHUTDOWN on GPIO_SD_B0_03 (pin K1) */
  gpio_pin_config_t READER_SHUTDOWN_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_03 (pin K1) */
  GPIO_PinInit(GPIO3, 15U, &READER_SHUTDOWN_config);

  /* GPIO configuration of READER_PWR on GPIO_SD_B0_05 (pin J2) */
  gpio_pin_config_t READER_PWR_config = {
      .direction = kGPIO_DigitalOutput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_SD_B0_05 (pin J2) */
  GPIO_PinInit(GPIO3, 17U, &READER_PWR_config);

  /* GPIO configuration of USB_STATUS on GPIO_EMC_00 (pin E3) */
  gpio_pin_config_t USB_STATUS_config = {
      .direction = kGPIO_DigitalInput,
      .outputLogic = 0U,
      .interruptMode = kGPIO_NoIntmode
  };
  /* Initialize GPIO functionality on GPIO_EMC_00 (pin E3) */
  GPIO_PinInit(GPIO4, 0U, &USB_STATUS_config);

  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_01_GPIO1_IO01, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_04_GPIO1_IO04, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_LPUART1_TX, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_00_LPI2C1_SCL, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_01_LPI2C1_SDA, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_02_LPUART2_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_03_LPUART2_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_04_GPIO1_IO20, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_05_GPIO1_IO21, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_08_GPIO1_IO24, 1U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_10_LPUART8_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_11_LPUART8_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_12_GPIO1_IO28, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_13_LPSPI3_SDI, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_14_LPSPI3_SDO, 0U); 
#if FSL_IOMUXC_DRIVER_VERSION >= MAKE_VERSION(2, 0, 4)
  IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B1_15_LPSPI3_SCK, 0U); 
#endif
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_00_GPIO2_IO16, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_12_LPUART5_TX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_B1_13_LPUART5_RX, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_EMC_00_GPIO4_IO00, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_03_GPIO3_IO15, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B0_05_GPIO3_IO17, 0U); 
  IOMUXC_SetPinMux(IOMUXC_GPIO_SD_B1_04_GPIO3_IO04, 0U); 
  IOMUXC_GPR->GPR26 = ((IOMUXC_GPR->GPR26 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR27 = ((IOMUXC_GPR->GPR27 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR28 = ((IOMUXC_GPR->GPR28 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR28_GPIO_MUX3_GPIO_SEL(0x00U) 
    );
  IOMUXC_GPR->GPR29 = ((IOMUXC_GPR->GPR29 &
    (~(BOARD_INITPINS_IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL_MASK))) 
      | IOMUXC_GPR_GPR29_GPIO_MUX4_GPIO_SEL(0x00U) 
    );
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_01_GPIO1_IO01, 0x30B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_02_GPIO1_IO02, 0x20B1U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_03_GPIO1_IO03, 0x20B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_04_GPIO1_IO04, 0x1079U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_13_LPUART1_RX, 0x10B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_00_LPI2C1_SCL, 0xE871U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_01_LPI2C1_SDA, 0xE871U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_06_GPIO1_IO22, 0xB0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_07_GPIO1_IO23, 0x10F0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_08_GPIO1_IO24, 0xA0B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_12_GPIO1_IO28, 0x1079U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_13_LPSPI3_SDI, 0x0110B0U); 
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_14_LPSPI3_SDO, 0x1079U); 
#if FSL_IOMUXC_DRIVER_VERSION >= MAKE_VERSION(2, 0, 4)
  IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B1_15_LPSPI3_SCK, 0x1079U); 
#endif
  IOMUXC_SetPinConfig(IOMUXC_GPIO_SD_B1_04_GPIO3_IO04, 0xB0U); 
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
